const springOnions = 'Spring Onions';
const garlicClove = 'Garlic Clove';
const chickenStock = 'Chicken Stock';
const vegetableStockCube = 'Vegetable Stock Cube';
const lemonJuice = 'Lemon Juice';
const ordinaryDrink = 'Ordinary Drink';
const highballGlass = 'Highball glass';
const powderedSugar = 'Powdered sugar';
const carbonatedWater = 'Carbonated water';
const juiceOf12 = 'Juice of 1/2 ';
const oldfashionedglass = 'Old-fashioned glass';
const sodaWater = 'Soda Water';

export const mealsIngredientChicken = {
  meals: [
    {
      strMeal: 'Brown Stew Chicken',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg',
      idMeal: '52940',
    },
    {
      strMeal: 'Chicken & mushroom Hotpot',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1511297945.jpg',
      idMeal: '52846',
    },
    {
      strMeal: 'Chicken Alfredo Primavera',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg',
      idMeal: '52796',
    },
    {
      strMeal: 'Chicken Basquaise',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wruvqv1511880994.jpg',
      idMeal: '52934',
    },
    {
      strMeal: 'Chicken Congee',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1529446352.jpg',
      idMeal: '52956',
    },
    {
      strMeal: 'Chicken Handi',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg',
      idMeal: '52795',
    },
    {
      strMeal: 'Kentucky Fried Chicken',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/xqusqy1487348868.jpg',
      idMeal: '52813',
    },
    {
      strMeal: 'Kung Pao Chicken',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1525872624.jpg',
      idMeal: '52945',
    },
    {
      strMeal: 'Pad See Ew',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg',
      idMeal: '52774',
    },
    {
      strMeal: 'Piri-piri chicken and slaw',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/hglsbl1614346998.jpg',
      idMeal: '53039',
    },
    {
      strMeal: 'Thai Green Curry',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg',
      idMeal: '52814',
    },
  ],
};

export const mealsNameSoup = {
  meals: [
    {
      idMeal: '52973',
      strMeal: 'Leblebi Soup',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Tunisian',
      strInstructions: 'Heat the oil in a large pot. Add the onion and cook until translucent.\r\nDrain the soaked chickpeas and add them to the pot together with the vegetable stock. Bring to the boil, then reduce the heat and cover. Simmer for 30 minutes.\r\nIn the meantime toast the cumin in a small ungreased frying pan, then grind them in a mortar. Add the garlic and salt and pound to a fine paste.\r\nAdd the paste and the harissa to the soup and simmer until the chickpeas are tender, about 30 minutes.\r\nSeason to taste with salt, pepper and lemon juice and serve hot.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/x2fw9e1560460636.jpg',
      strTags: 'Soup',
      strYoutube: 'https://www.youtube.com/watch?v=BgRifcCwinY',
      strIngredient1: 'Olive Oil',
      strIngredient2: 'Onion',
      strIngredient3: 'Chickpeas',
      strIngredient4: 'Vegetable Stock',
      strIngredient5: 'Cumin',
      strIngredient6: 'Garlic',
      strIngredient7: 'Salt',
      strIngredient8: 'Harissa Spice',
      strIngredient9: 'Pepper',
      strIngredient10: 'Lime',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 tbs',
      strMeasure2: '1 medium finely diced',
      strMeasure3: '250g',
      strMeasure4: '1.5L',
      strMeasure5: '1 tsp ',
      strMeasure6: '5 cloves',
      strMeasure7: '1/2 tsp',
      strMeasure8: '1 tsp ',
      strMeasure9: 'Pinch',
      strMeasure10: '1/2 ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://allrecipes.co.uk/recipe/43419/leblebi--tunisian-chickpea-soup-.aspx',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52941',
      strMeal: 'Red Peas Soup',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'Jamaican',
      strInstructions: 'Wash and rinse the dried kidney beans.. then cover with water in a deep bowl. Remember as they soak they will expand to at least triple the size they were originally so add a lot of water to the bowl. Soak them overnight or for at least 2 hrs to make the cooking step go quicker. I tossed out the water they were soaked in after it did the job.\r\n\r\nHave your butcher cut the salted pigtail into 2 inch pieces as it will be very difficult to cut with an ordinary kitchen knife. Wash, then place a deep pot with water and bring to a boil. Cook for 20 minutes, then drain + rinse and repeat (boil again in water). The goal is to make the pieces of pig tails tender and to remove most of the salt it was cured in.\r\n\r\nTime to start the soup. Place everything in the pot (except the flour and potato), then cover with water and place on a high flame to bring to a boil. As it comes to a boil, skim off any scum/froth at the top and discard. Reduce the heat to a gentle boil and allow it to cook for 1 hr and 15 mins.. basically until the beans are tender and start falling apart.\r\n\r\nIt’s now time to add the potato (and Yams etc if you’re adding it) as well as the coconut milk and continue cooking for 15 minutes.\r\n\r\nNow is a good time to start making the basic dough for the spinner dumplings. Mix the flour and water (add a pinch of salt if you want) until you have a soft/smooth dough. allow it to rest for 5 minutes, then pinch of a tablespoon at a time and roll between your hands to form a cigarette shape.\r\n\r\nAdd them to the pot, stir well and continue cooking for another 15 minutes on a rolling boil.\r\n\r\nYou’ll notice that I didn’t add any salt to the pot as the remaining salt from the salted pigtails will be enough to properly season this dish. However you can taste and adjust accordingly. Lets recap the timing part of things so you’re not confused. Cook the base of the soup for 1 hr and 15 minute or until tender, then add the potatoes and cook for 15 minutes, then add the dumplings and cook for a further 15 minutes. Keep in mind that this soup will thicken quite a bit as it cools.\r\n\r\nWhile this is not a traditional recipe to any one specific island, versions of this soup (sometimes called stewed peas) can be found throughout the Caribbean, Latin America and Africa. A hearty bowl of this soup will surely give you the sleepies (some may call it ethnic fatigue). You can certainly freeze the leftovers and heat it up another day.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sqpqtp1515365614.jpg',
      strTags: 'Soup,SideDish',
      strYoutube: 'https://www.youtube.com/watch?v=1ogCfDXotMw',
      strIngredient1: 'Kidney Beans',
      strIngredient2: 'Carrots',
      strIngredient3: springOnions,
      strIngredient4: 'Thyme',
      strIngredient5: 'Onion',
      strIngredient6: 'Black Pepper',
      strIngredient7: 'Red Pepper',
      strIngredient8: garlicClove,
      strIngredient9: 'Allspice',
      strIngredient10: 'Beef',
      strIngredient11: 'Water',
      strIngredient12: 'Potatoes',
      strIngredient13: 'Plain Flour',
      strIngredient14: 'Water',
      strIngredient15: 'Coconut Milk',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 cups ',
      strMeasure2: '1 large',
      strMeasure3: '2 chopped',
      strMeasure4: '4 sprigs',
      strMeasure5: '1 Diced',
      strMeasure6: '1/2 tsp',
      strMeasure7: '2 chopped',
      strMeasure8: '4 Mashed',
      strMeasure9: '1 tbs',
      strMeasure10: '2 Lbs',
      strMeasure11: '2L',
      strMeasure12: '4',
      strMeasure13: '1 cup ',
      strMeasure14: '1/4 cup',
      strMeasure15: '1 cup ',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://caribbeanpot.com/caribbean-red-peas-soup/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52955',
      strMeal: 'Egg Drop Soup',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Chinese',
      strInstructions: 'In a wok add chicken broth and wait for it to boil.\r\nNext add salt, sugar, white pepper, sesame seed oil.\r\nWhen the chicken broth is boiling add the vegetables to the wok.\r\nTo thicken the sauce, whisk together 1 Tablespoon of cornstarch and 2 Tablespoon of water in a bowl and slowly add to your soup until it\'s the right thickness.\r\nNext add 1 egg slightly beaten with a knife or fork and add it to the soup slowly and stir for 8 seconds\r\nServe the soup in a bowl and add the green onions on top.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1529446137.jpg',
      strTags: 'Soup,Baking,Calorific',
      strYoutube: 'https://www.youtube.com/watch?v=9XpzHm9QpZg',
      strIngredient1: chickenStock,
      strIngredient2: 'Salt',
      strIngredient3: 'Sugar',
      strIngredient4: 'Pepper',
      strIngredient5: 'Sesame Seed Oil',
      strIngredient6: 'Peas',
      strIngredient7: 'Mushrooms',
      strIngredient8: 'Cornstarch',
      strIngredient9: 'Water',
      strIngredient10: springOnions,
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '3 cups ',
      strMeasure2: '1/4 tsp',
      strMeasure3: '1/4 tsp',
      strMeasure4: 'pinch',
      strMeasure5: '1 tsp ',
      strMeasure6: '1/3 cup',
      strMeasure7: '1/3 cup',
      strMeasure8: '1 tbs',
      strMeasure9: '2 tbs',
      strMeasure10: '1/4 cup',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://sueandgambo.com/pages/egg-drop-soup',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52925',
      strMeal: 'Split Pea Soup',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Canadian',
      strInstructions: 'Put the gammon in a very large pan with 2 litres water and bring to the boil. Remove from the heat and drain off the water – this helps to get rid of some of the saltiness. Recover with 2 litres cold water and bring to the boil again. Put everything but the frozen peas into the pan and bring to the boil. Reduce to a simmer and cook for 1½-2½ hrs, topping up the water as and when you need to, to a similar level it started at. As the ham cooks and softens, you can halve it if you want, so it is all submerged under the liquid. When the ham is tender enough to pull into shreds, it is ready.\r\nLift out the ham, peel off and discard the skin. While it is still hot (wear a clean pair of rubber gloves), shred the meat. Remove bay from the soup and stir in the frozen peas. Simmer for 1 min, then blend until smooth. Add a splash of water if too thick, and return to the pan to heat through if it has cooled, or if you are making ahead.\r\nWhen you are ready to serve, mix the hot soup with most of the ham – gently reheat if made ahead. Serve in bowls with the remaining ham scattered on top, and eat with crusty bread and butter.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/xxtsvx1511814083.jpg',
      strTags: 'Soup,Warm',
      strYoutube: 'https://www.youtube.com/watch?v=qdhWz7qAaCU',
      strIngredient1: 'Ham',
      strIngredient2: 'Peas',
      strIngredient3: 'Onions',
      strIngredient4: 'Carrots',
      strIngredient5: 'Bay Leaves',
      strIngredient6: 'Celery',
      strIngredient7: 'Frozen Peas',
      strIngredient8: 'Bread',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1kg',
      strMeasure2: '200g (soaked overnight)',
      strMeasure3: '2 chopped',
      strMeasure4: '2 chopped',
      strMeasure5: '2',
      strMeasure6: '1 chopped',
      strMeasure7: '300g',
      strMeasure8: 'to serve',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/1022639/split-pea-and-green-pea-smoked-ham-soup',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52903',
      strMeal: 'French Onion Soup',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'French',
      strInstructions: 'Melt the butter with the oil in a large heavy-based pan. Add the onions and fry with the lid on for 10 mins until soft. Sprinkle in the sugar and cook for 20 mins more, stirring frequently, until caramelised. The onions should be really golden, full of flavour and soft when pinched between your fingers. Take care towards the end to ensure that they don’t burn.\r\nAdd the garlic for the final few mins of the onions’ cooking time, then sprinkle in the flour and stir well. Increase the heat and keep stirring as you gradually add the wine, followed by the hot stock. Cover and simmer for 15-20 mins.\r\nTo serve, turn on the grill, and toast the bread. Ladle the soup into heatproof bowls. Put a slice or two of toast on top of the bowls of soup, and pile on the cheese. Grill until melted. Alternatively, you can complete the toasts under the grill, then serve them on top.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/xvrrux1511783685.jpg',
      strTags: 'Soup',
      strYoutube: 'https://www.youtube.com/watch?v=-DLDMQucqDI',
      strIngredient1: 'Butter',
      strIngredient2: 'Olive Oil',
      strIngredient3: 'Onion',
      strIngredient4: 'Sugar',
      strIngredient5: garlicClove,
      strIngredient6: 'Plain Flour',
      strIngredient7: 'Dry White Wine',
      strIngredient8: 'Beef Stock',
      strIngredient9: 'Bread',
      strIngredient10: 'Gruyère',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '50g',
      strMeasure2: '1 tbs',
      strMeasure3: '1 kg',
      strMeasure4: '1 tsp ',
      strMeasure5: '4 sliced',
      strMeasure6: '2 tbs',
      strMeasure7: '250ml',
      strMeasure8: '1L',
      strMeasure9: '4 sliced',
      strMeasure10: '140g',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/3020694/french-onion-soup',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52954',
      strMeal: 'Hot and Sour Soup',
      strDrinkAlternate: null,
      strCategory: 'Pork',
      strArea: 'Chinese',
      strInstructions: 'STEP 1 - MAKING THE SOUP\r\nIn a wok add chicken broth and wait for it to boil.\r\nNext add salt, sugar, sesame seed oil, white pepper, hot pepper sauce, vinegar and soy sauce and stir for few seconds.\r\nAdd Tofu, mushrooms, black wood ear mushrooms to the wok.\r\nTo thicken the sauce, whisk together 1 Tablespoon of cornstarch and 2 Tablespoon of water in a bowl and slowly add to your soup until it\'s the right thickness.\r\nNext add 1 egg slightly beaten with a knife or fork and add it to the soup and stir for 8 seconds\r\nServe the soup in a bowl and add the bbq pork and sliced green onions on top.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1529445893.jpg',
      strTags: 'Soup',
      strYoutube: 'https://www.youtube.com/watch?v=KgV9Zq3aSTo',
      strIngredient1: 'Mushrooms',
      strIngredient2: 'Wood Ear Mushrooms',
      strIngredient3: 'Tofu',
      strIngredient4: 'Pork',
      strIngredient5: chickenStock,
      strIngredient6: 'Salt',
      strIngredient7: 'Sugar',
      strIngredient8: 'Sesame Seed Oil',
      strIngredient9: 'Pepper',
      strIngredient10: 'Hotsauce',
      strIngredient11: 'Vinegar',
      strIngredient12: 'Soy Sauce',
      strIngredient13: 'Cornstarch',
      strIngredient14: 'Water',
      strIngredient15: springOnions,
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1/3 cup',
      strMeasure2: '1/3 cup',
      strMeasure3: '2/3 Cup',
      strMeasure4: '1/2 cup ',
      strMeasure5: '2-1/2 cups',
      strMeasure6: '1/2 tsp',
      strMeasure7: '1/4 tsp',
      strMeasure8: '1 tsp ',
      strMeasure9: '1/4 tsp',
      strMeasure10: '1/2 tsp',
      strMeasure11: '1-½ cups',
      strMeasure12: '1 tsp ',
      strMeasure13: '1 tbs',
      strMeasure14: '2 tbs',
      strMeasure15: '1/4 cup',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://sueandgambo.com/pages/chinese-hot-and-sour-soup',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52841',
      strMeal: 'Creamy Tomato Soup',
      strDrinkAlternate: null,
      strCategory: 'Starter',
      strArea: 'British',
      strInstructions: 'Put the oil, onions, celery, carrots, potatoes and bay leaves in a big casserole dish, or two saucepans. Fry gently until the onions are softened – about 10-15 mins. Fill the kettle and boil it.\r\nStir in the tomato purée, sugar, vinegar, chopped tomatoes and passata, then crumble in the stock cubes. Add 1 litre boiling water and bring to a simmer. Cover and simmer for 15 mins until the potato is tender, then remove the bay leaves. Purée with a stick blender (or ladle into a blender in batches) until very smooth. Season to taste and add a pinch more sugar if it needs it. The soup can now be cooled and chilled for up to 2 days, or frozen for up to 3 months.\r\nTo serve, reheat the soup, stirring in the milk – try not to let it boil. Serve in small bowls with cheesy sausage rolls.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/stpuws1511191310.jpg',
      strTags: 'Baking',
      strYoutube: 'https://www.youtube.com/watch?v=lBhwjjUiFk4',
      strIngredient1: 'Olive Oil',
      strIngredient2: 'Onions',
      strIngredient3: 'Celery',
      strIngredient4: 'Carrots',
      strIngredient5: 'Potatoes',
      strIngredient6: 'Bay Leaf',
      strIngredient7: 'Tomato Puree',
      strIngredient8: 'Sugar',
      strIngredient9: 'White Vinegar',
      strIngredient10: 'Chopped Tomatoes',
      strIngredient11: 'Passata',
      strIngredient12: vegetableStockCube,
      strIngredient13: 'Whole Milk',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '3 tbsp',
      strMeasure2: '2 chopped',
      strMeasure3: '2 sticks',
      strMeasure4: '300g',
      strMeasure5: '500g',
      strMeasure6: '4',
      strMeasure7: '5 tblsp ',
      strMeasure8: '2 tblsp ',
      strMeasure9: '2 tblsp ',
      strMeasure10: '1½ kg',
      strMeasure11: '500g',
      strMeasure12: '3',
      strMeasure13: '400ml',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/2604646/creamy-tomato-soup',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52972',
      strMeal: 'Tunisian Lamb Soup',
      strDrinkAlternate: null,
      strCategory: 'Lamb',
      strArea: 'Tunisian',
      strInstructions: 'Add the lamb to a casserole and cook over high heat. When browned, remove from the heat and set aside.\r\nKeep a tablespoon of fat in the casserole and discard the rest. Reduce to medium heat then add the garlic, onion and spinach and cook until the onion is translucent and the spinach wilted or about 5 minutes.\r\nReturn the lamb to the casserole with the onion-spinach mixture, add the tomato puree, cumin, harissa, chicken, chickpeas, lemon juice, salt and pepper in the pan. Simmer over low heat for about 20 minutes.\r\nAdd the pasta and cook for 15 minutes or until pasta is cooked.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/t8mn9g1560460231.jpg',
      strTags: 'Soup',
      strYoutube: 'https://www.youtube.com/watch?v=w1qgTQmLRe4',
      strIngredient1: 'Lamb Mince',
      strIngredient2: 'Garlic',
      strIngredient3: 'Onion',
      strIngredient4: 'Spinach',
      strIngredient5: 'Tomato Puree',
      strIngredient6: 'Cumin',
      strIngredient7: chickenStock,
      strIngredient8: 'Harissa Spice',
      strIngredient9: 'Chickpeas',
      strIngredient10: lemonJuice,
      strIngredient11: 'Macaroni',
      strIngredient12: 'Salt',
      strIngredient13: 'Pepper',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '500g',
      strMeasure2: '2 cloves minced',
      strMeasure3: '1',
      strMeasure4: '300g',
      strMeasure5: '3 tbs',
      strMeasure6: '1 tbs',
      strMeasure7: '1 Litre',
      strMeasure8: '3 tsp',
      strMeasure9: '400g',
      strMeasure10: '1/2 ',
      strMeasure11: '150g',
      strMeasure12: 'Pinch',
      strMeasure13: 'Pinch',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://allrecipes.co.uk/recipe/16694/tunisian-lamb-soup.aspx',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53047',
      strMeal: 'Moroccan Carrot Soup',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Moroccan',
      strInstructions: 'Step 1\r\nPreheat oven to 180° C.\r\nStep 2\r\nCombine carrots, onion, garlic, cumin seeds, coriander seeds, salt and olive oil in a bowl and mix well. Transfer on a baking tray.\r\nStep 3\r\nPut the baking tray in preheated oven and roast for 10-12 minutes or till carrots soften. Remove from heat and cool.\r\nStep 4\r\nGrind the baked carrot mixture along with some water to make a smooth paste and strain in a bowl.\r\nStep 5\r\nHeat the carrot mixture in a non-stick pan. Add two cups of water and bring to a boil. Add garam masala powder and mix. Add salt and mix well.\r\nStep 6\r\nRemove from heat, add lemon juice and mix well.\r\nStep 7\r\nServe hot.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/jcr46d1614763831.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=7tDWOpnIhok',
      strIngredient1: 'Carrots',
      strIngredient2: 'Onion',
      strIngredient3: garlicClove,
      strIngredient4: 'Cumin',
      strIngredient5: 'Coriander',
      strIngredient6: 'Olive Oil',
      strIngredient7: 'Garam Masala',
      strIngredient8: lemonJuice,
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '6 chopped',
      strMeasure2: '1 sliced',
      strMeasure3: '4',
      strMeasure4: '1 tsp ',
      strMeasure5: '1/2 tsp',
      strMeasure6: '1 tbs',
      strMeasure7: '1/4 tsp',
      strMeasure8: '1 tsp ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.sanjeevkapoor.com/Recipe/Moroccan-Carrot-Soup.html',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52842',
      strMeal: 'Broccoli & Stilton soup',
      strDrinkAlternate: null,
      strCategory: 'Starter',
      strArea: 'British',
      strInstructions: 'Heat the rapeseed oil in a large saucepan and then add the onions. Cook on a medium heat until soft. Add a splash of water if the onions start to catch.\r\n\r\nAdd the celery, leek, potato and a knob of butter. Stir until melted, then cover with a lid. Allow to sweat for 5 minutes. Remove the lid.\r\n\r\nPour in the stock and add any chunky bits of broccoli stalk. Cook for 10 – 15 minutes until all the vegetables are soft.\r\n\r\nAdd the rest of the broccoli and cook for a further 5 minutes. Carefully transfer to a blender and blitz until smooth. Stir in the stilton, allowing a few lumps to remain. Season with black pepper and serve.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tvvxpv1511191952.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=_HgVLpmNxTY',
      strIngredient1: 'Rapeseed Oil',
      strIngredient2: 'Onion',
      strIngredient3: 'Celery',
      strIngredient4: 'Leek',
      strIngredient5: 'Potatoes',
      strIngredient6: 'Butter',
      strIngredient7: 'Vegetable Stock',
      strIngredient8: 'Broccoli',
      strIngredient9: 'Stilton Cheese',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 tblsp ',
      strMeasure2: '1 finely chopped ',
      strMeasure3: '1',
      strMeasure4: '1 sliced',
      strMeasure5: '1 medium',
      strMeasure6: '1 knob',
      strMeasure7: '1 litre hot',
      strMeasure8: '1 Head chopped',
      strMeasure9: '140g',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/1940679/broccoli-and-stilton-soup',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52981',
      strMeal: 'Snert (Dutch Split Pea Soup)',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Dutch',
      strInstructions: 'Gather the ingredients.\r\n\r\nIn a large soup pot, bring water, split peas, pork belly or bacon, pork chop, and bouillon cube to a boil. Reduce the heat to a simmer, cover and let cook for 45 minutes, stirring occasionally and skimming off any foam that rises to the top. \r\n\r\nRemove the pork chop, debone, and thinly slice the meat. Set aside.\r\n\r\nAdd the celery, carrots, potato, onion, leek, and celeriac to the soup. Return to the boil, reduce the heat to a simmer and let cook, uncovered, for another 30 minutes, adding a little extra water if the ingredients start to stick to the bottom of the pot.\r\n\r\nAdd the smoked sausage for the last 15 minutes of cooking time. When the vegetables are tender, remove the bacon and smoked sausage, slice thinly and set aside.\r\n\r\nIf you prefer a smooth consistency, purée the soup with a stick blender. Season to taste with salt and pepper. Add the meat back to the soup, setting some slices of rookworst aside.\r\n\r\nServe in heated bowls or soup plates, garnished with slices of rookworst and chopped celery leaf.\r\n\r\nEnjoy!',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/9ptx0a1565090843.jpg',
      strTags: 'Soup,Cake',
      strYoutube: 'https://www.youtube.com/watch?v=5YV0sJLtLt8',
      strIngredient1: 'Water',
      strIngredient2: 'Peas',
      strIngredient3: 'Pork',
      strIngredient4: vegetableStockCube,
      strIngredient5: 'Celery',
      strIngredient6: 'Carrots',
      strIngredient7: 'Potatoes',
      strIngredient8: 'Onion',
      strIngredient9: 'Leek',
      strIngredient10: 'Celeriac',
      strIngredient11: 'Sausages',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2L',
      strMeasure2: '300g',
      strMeasure3: '100g ',
      strMeasure4: '1',
      strMeasure5: '2',
      strMeasure6: '2',
      strMeasure7: '1 large',
      strMeasure8: '1 small',
      strMeasure9: '1 small',
      strMeasure10: '1 cup ',
      strMeasure11: '1 pound',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.thespruceeats.com/traditional-dutch-split-pea-soup-1129011',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53059',
      strMeal: 'Mushroom soup with buckwheat',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Croatian',
      strInstructions: 'Chop the onion and garlic, slice the mushrooms and wash the buckwheat. Heat the oil and lightly sauté the onion. Add the mushrooms and the garlic and continue to sauté. Add the salt, vegetable seasoning, buckwheat and the bay leaf and cover with water. Simmer gently and just before it is completely cooked, add pepper, sour cream mixed with flour, the chopped parsley and vinegar to taste.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1ngcbf1628770793.jpg',
      strTags: 'Warming, Soup',
      strYoutube: 'https://www.youtube.com/watch?v=M1ok7mG9-Qc',
      strIngredient1: 'Mushrooms',
      strIngredient2: 'Buckwheat',
      strIngredient3: 'Vegetable Oil',
      strIngredient4: 'Onion',
      strIngredient5: 'Garlic',
      strIngredient6: 'Bay Leaf',
      strIngredient7: vegetableStockCube,
      strIngredient8: 'Sour Cream',
      strIngredient9: 'White Wine Vinegar',
      strIngredient10: 'Parsley',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '150g',
      strMeasure2: '50g',
      strMeasure3: '4 tbs',
      strMeasure4: '40g',
      strMeasure5: '2 cloves',
      strMeasure6: '1',
      strMeasure7: '1tbsp',
      strMeasure8: '50 ml ',
      strMeasure9: 'Dash',
      strMeasure10: 'Top',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53020',
      strMeal: 'Rosół (Polish Chicken Soup)',
      strDrinkAlternate: null,
      strCategory: 'Chicken',
      strArea: 'Polish',
      strInstructions: 'Add chicken to a large Dutch oven or stock pot \r\nCover with water\r\nBring to a boil and simmer for 2 to 2 1/2 hours, skimming any impurities off the top to insure a clear broth\r\nIf your pot is big enough, add the vegetables and spices for the last hour of the cooking time\r\nMy Dutch oven wasn’t big enough to hold everything, just the chicken and other bones filled the pot, so I cooked the meat/bones for the full cooking time, then removed them, and cooked the vegetables and spices separately\r\nStrain everything out of the broth\r\nBone the chicken, pulling the meat into large chunks\r\nSlice the carrots\r\nReturn the chicken and carrots to the broth\r\nCook noodles according to package instructions if you’re using them\r\nAdd noodles to bowl and then top with hot soup',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/lx1kkj1593349302.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=AU60fxyxXGw',
      strIngredient1: 'Chicken Legs',
      strIngredient2: 'Onions',
      strIngredient3: 'Carrots',
      strIngredient4: 'Leek',
      strIngredient5: 'Celery',
      strIngredient6: 'Cabbage',
      strIngredient7: 'Cloves',
      strIngredient8: 'Allspice',
      strIngredient9: 'Bay Leaf',
      strIngredient10: 'Parsley',
      strIngredient11: 'Dill',
      strIngredient12: 'Pepper',
      strIngredient13: 'Salt',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '4 Chopped',
      strMeasure2: '2 large',
      strMeasure3: '5 chopped',
      strMeasure4: '1 chopped',
      strMeasure5: '1 small',
      strMeasure6: '1/4 ',
      strMeasure7: '1 whole',
      strMeasure8: '1tsp',
      strMeasure9: '2',
      strMeasure10: '4 sprigs',
      strMeasure11: '4 sprigs',
      strMeasure12: '1 tsp ',
      strMeasure13: '1 tbs',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://polishhousewife.com/rosol-polish-chicken-soup/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const mealsIngredientXablau = { meals: null };

export const mealsNameArrabiata = {
  meals: [
    {
      idMeal: '52771',
      strMeal: 'Spicy Arrabiata Penne',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Italian',
      strInstructions: 'Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg',
      strTags: 'Pasta,Curry',
      strYoutube: 'https://www.youtube.com/watch?v=1IszT_guI08',
      strIngredient1: 'penne rigate',
      strIngredient2: 'olive oil',
      strIngredient3: 'garlic',
      strIngredient4: 'chopped tomatoes',
      strIngredient5: 'red chile flakes',
      strIngredient6: 'italian seasoning',
      strIngredient7: 'basil',
      strIngredient8: 'Parmigiano-Reggiano',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: null,
      strIngredient17: null,
      strIngredient18: null,
      strIngredient19: null,
      strIngredient20: null,
      strMeasure1: '1 pound',
      strMeasure2: '1/4 cup',
      strMeasure3: '3 cloves',
      strMeasure4: '1 tin ',
      strMeasure5: '1/2 teaspoon',
      strMeasure6: '1/2 teaspoon',
      strMeasure7: '6 leaves',
      strMeasure8: 'spinkling',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: null,
      strMeasure17: null,
      strMeasure18: null,
      strMeasure19: null,
      strMeasure20: null,
      strSource: null,
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

export const drinksIngredientXablau = { drinks: null };

export const drinksNameGin = {
  drinks: [
    {
      idDrink: '11410',
      strDrink: 'Gin Fizz',
      strDrinkAlternate: null,
      strTags: 'IBA,Classic',
      strVideo: 'https://www.youtube.com/watch?v=obGhGNUKx30',
      strCategory: ordinaryDrink,
      strIBA: 'Unforgettables',
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Shake all ingredients with ice cubes, except soda water. Pour into glass. Top with soda water.',
      strInstructionsES: null,
      strInstructionsDE: 'Alle Zutaten mit Eiswürfel schütteln, außer Sodawasser. In das Glas gießen. Mit Sodawasser auffüllen.',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare tutti gli ingredienti con cubetti di ghiaccio, tranne l\'acqua gassata. Versare nel bicchiere. Completare con acqua gassata.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/drtihp1606768397.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Lemon',
      strIngredient3: powderedSugar,
      strIngredient4: carbonatedWater,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: juiceOf12,
      strMeasure3: '1 tsp ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://commons.wikimedia.org/wiki/File:15-09-26-RalfR-WLC-0032.jpg',
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2017-09-02 12:29:32',
    },
    {
      idDrink: '11417',
      strDrink: 'Gin Sour',
      strDrinkAlternate: null,
      strTags: 'Sour',
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Whiskey sour glass',
      strInstructions: 'In a shaker half-filled with ice cubes, combine the gin, lemon juice, and sugar. Shake well. Strain into a sour glass and garnish with the orange slice and the cherry.',
      strInstructionsES: null,
      strInstructionsDE: 'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, Gin, Zitronensaft und Zucker mischen. Gut schütteln. In ein Sour Glas abseihen und mit der Orangenscheibe und der Kirsche garnieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'In uno shaker riempito a metà con cubetti di ghiaccio, unisci il gin, il succo di limone e lo zucchero.Filtrare in un bicchiere e guarnire con la fetta d\'arancia e la ciliegia.Agitare bene.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/noxp7e1606769224.jpg',
      strIngredient1: 'Gin',
      strIngredient2: lemonJuice,
      strIngredient3: 'Sugar',
      strIngredient4: 'Orange',
      strIngredient5: 'Maraschino cherry',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1/2 tsp superfine ',
      strMeasure4: '1 ',
      strMeasure5: '1 ',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://pixabay.com/photos/gin-and-tonic-gin-sour-cocktail-4499713/',
      strImageAttribution: 'Inactive account – ID 7303458',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2017-09-08 16:12:03',
    },
    {
      idDrink: '11936',
      strDrink: 'Pink Gin',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'White wine glass',
      strInstructions: 'Pour the bitters into a wine glass. Swirl the glass to coat the inside with the bitters, shake out the excess. Pour the gin into the glass. Do not add ice.',
      strInstructionsES: null,
      strInstructionsDE: 'Den Bitter in ein Weinglas gießen. Das Glas umrühren, um die Innenseite mit dem Bitter zu überziehen, den Überschuss ausschütten. Gießen Sie den Gin in das Glas. Füge kein Eis hinzu.',
      strInstructionsFR: null,
      strInstructionsIT: 'Distribuire nei bicchieri i cubetti di ghiaccio, i lamponi, il pepe e il gin e versare l’acqua tonica.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/qyr51e1504888618.jpg',
      strIngredient1: 'Bitters',
      strIngredient2: 'Gin',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '3 dashes ',
      strMeasure2: '2 oz ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-08 17:36:58',
    },
    {
      idDrink: '11408',
      strDrink: 'Gin Daisy',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: oldfashionedglass,
      strInstructions: 'In a shaker half-filled with ice cubes, combine the gin, lemon juice, sugar, and grenadine. Shake well. Pour into an old-fashioned glass and garnish with the cherry and the orange slice.',
      strInstructionsES: null,
      strInstructionsDE: 'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, Wein, Zitronensaft, Zucker und Grenadine vermengen. Gut schütteln. In ein old-fashioned Glas geben und mit der Kirsche und der Orangenscheibe garnieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'In uno shaker riempito a metà con cubetti di ghiaccio, unire il vino, il succo di limone, lo zucchero e la granatina.Versare in un bicchiere vecchio stile e guarnire con la ciliegia e la fetta d\'arancia.Agitare bene.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/z6e22f1582581155.jpg',
      strIngredient1: 'Gin',
      strIngredient2: lemonJuice,
      strIngredient3: 'Sugar',
      strIngredient4: 'Grenadine',
      strIngredient5: 'Maraschino cherry',
      strIngredient6: 'Orange',
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1/2 tsp superfine ',
      strMeasure4: '1/2 tsp ',
      strMeasure5: '1 ',
      strMeasure6: '1 ',
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-11-10 23:19:04',
    },
    {
      idDrink: '11415',
      strDrink: 'Gin Sling',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: oldfashionedglass,
      strInstructions: 'Dissolve powdered sugar in mixture of water and juice of lemon. Add gin. Pour into an old-fashioned glass over ice cubes and stir. Add the twist of orange peel and serve.',
      strInstructionsES: null,
      strInstructionsDE: 'Puderzucker in einer Mischung aus Wasser und Zitronensaft auflösen. Gin hinzufügen. In ein old-fashioned Glas über Eiswürfel gießen und umrühren. Die  Orangenspirale hinzufügen und servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Sciogliere lo zucchero a velo in una miscela di acqua e succo di limone. Aggiungi il gin. Versare in un bicchiere vecchio stile con dei cubetti di ghiaccio e mescolare.Aggiungere la scorza d\'arancia e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/8cl9sm1582581761.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Lemon',
      strIngredient3: powderedSugar,
      strIngredient4: 'Water',
      strIngredient5: 'Orange peel',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: juiceOf12,
      strMeasure3: '1 tsp ',
      strMeasure4: '1 tsp ',
      strMeasure5: 'Twist of ',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://www.thecocktaildb.com/drink/11415',
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2017-09-08 16:10:40',
    },
    {
      idDrink: '11416',
      strDrink: 'Gin Smash',
      strDrinkAlternate: null,
      strTags: 'Citrus,StrongFlavor',
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: oldfashionedglass,
      strInstructions: 'Muddle sugar with carbonated water and mint sprigs in an old-fashioned glass. Add gin and 1 ice cube. Stir, add the orange slice and the cherry, and serve.',
      strInstructionsES: null,
      strInstructionsDE: 'Den Zucker mit kohlensäurehaltigem Wasser und Minzzweigen in einem old-fashioned Glas vermengen. Gin und 1 Eiswürfel dazugeben. Umrühren, die Orangenscheibe und die Kirsche dazugeben und servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Pestare lo zucchero con acqua gassata e rametti di menta in un bicchiere vecchio stile.Aggiungi il gin e 1 cubetto di ghiaccio.Mescolate, aggiungete la fetta d\'arancia e la ciliegia e servite.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/iprva61606768774.jpg',
      strIngredient1: 'Gin',
      strIngredient2: carbonatedWater,
      strIngredient3: 'Sugar',
      strIngredient4: 'Mint',
      strIngredient5: 'Orange',
      strIngredient6: 'Cherry',
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '1 oz ',
      strMeasure3: '1 cube ',
      strMeasure4: '4 ',
      strMeasure5: '1 slice ',
      strMeasure6: '1 ',
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://commons.wikimedia.org/wiki/File:Gin_Basil_Smash.jpg',
      strImageAttribution: '© Erich Wagner (www.eventografie.de)',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2017-09-08 16:14:16',
    },
    {
      idDrink: '11420',
      strDrink: 'Gin Toddy',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: oldfashionedglass,
      strInstructions: 'Mix powdered sugar and water in an old-fashioned glass. Add gin and one ice cube. Stir, add the twist of lemon peel, and serve.',
      strInstructionsES: null,
      strInstructionsDE: 'Puderzucker und Wasser in einem old-fashioned Glas mischen. Gin und einen Eiswürfel dazugeben. Umrühren, Zitronenschale hinzufügen und servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Mescolare lo zucchero a velo e l\'acqua in un bicchiere vecchio stile. Aggiungi il gin e un cubetto di ghiaccio. Mescolare, aggiungere la scorza di limone e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/jxstwf1582582101.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Water',
      strIngredient3: powderedSugar,
      strIngredient4: 'Lemon peel',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '2 tsp ',
      strMeasure3: '1/2 tsp ',
      strMeasure4: '1 twist of ',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2017-09-07 22:45:24',
    },
    {
      idDrink: '178365',
      strDrink: 'Gin Tonic',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Fill a highball glass with ice, pour the gin, top with tonic water and squeeze a lemon wedge and garnish with a lemon wedge.',
      strInstructionsES: null,
      strInstructionsDE: 'Füllen Sie ein Highball-Glas mit Eis, gießen Sie den Gin ein, gießen Sie Tonic Water darüber und drücken Sie eine Zitronenscheibe aus und garnieren Sie sie mit einer Zitronenscheibe.',
      strInstructionsFR: null,
      strInstructionsIT: 'Colmate un bicchiere highball di ghiaccio, versate il gin, colmate con acqua tonica e spremete uno spicchio di limone e guarnite con una fetta di limone. ',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/qcgz0t1643821443.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Tonic Water',
      strIngredient3: 'Lemon Peel',
      strIngredient4: 'Ice',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '4 cl',
      strMeasure2: '10 cl',
      strMeasure3: '1 Slice',
      strMeasure4: 'cubes',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://www.brunovanzan.com/wp-content/uploads/2020/01/gin-tonic.png',
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: null,
    },
    {
      idDrink: '178366',
      strDrink: 'Gin Lemon',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'For the preparation of the gin lemon you will not need the shaker. Fill the tumbler with ice, pour the gin and lemonade over it. Gently mix and decorate with a slice of lemon. Those who prefer can also add a few mint leaves. Your gin lemon is ready to be served.',
      strInstructionsES: null,
      strInstructionsDE: 'Für die Zubereitung des Gin Lemon benötigen Sie den Shaker nicht. Tumbler mit Eis füllen, Gin und Limonade darüber gießen. Vorsichtig mischen und mit einer Zitronenscheibe dekorieren. Wer möchte, kann auch noch ein paar Minzblätter hinzugeben. Ihr Gin Lemon ist servierfertig.',
      strInstructionsFR: null,
      strInstructionsIT: 'Per la preparazione del gin lemon non vi servirà lo shaker. Riempite il tumbler con il ghiaccio, versateci sopra il gin e la limonata. Mescolate delicatamente e decorate con una fetta di limone. Chi preferisce potrà aggiungere anche qualche fogliolina di menta. Il vostro gin lemon è pronto per essere servito.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/yhzvk91643821739.jpg',
      strIngredient1: 'Gin',
      strIngredient2: lemonJuice,
      strIngredient3: 'Lemon Peel',
      strIngredient4: 'Ice',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '6 cl',
      strMeasure2: '8 cl',
      strMeasure3: '1 Slice',
      strMeasure4: 'cubes',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://it.inshaker.com/uploads/cocktail/hires/368/1629735247-%D0%94%D0%B6%D0%B8%D0%BD_%D1%82%D0%BE%D0%BD%D0%B8%D0%BA.jpg',
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: null,
    },
    {
      idDrink: '11407',
      strDrink: 'Gin Cooler',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Collins glass',
      strInstructions: 'Stir powdered sugar and 2 oz. carbonated water in a collins glass. Fill glass with ice and add gin. Fill with carbonated water and stir. Add the lemon peel and the orange spiral so that the end of the orange spiral dangles over rim of glass.',
      strInstructionsES: null,
      strInstructionsDE: 'Puderzucker und 6 cl. kohlensäurehaltiges Wasser in einem Collins-Glas verrühren. Das Glas mit Eis füllen und Gin hinzufügen. Mit kohlensäurehaltigem Wasser auffüllen und umrühren. Fügen Sie die Zitronenschale und die Orangenspirale so hinzu, dass das Ende der Orangenspirale über den Glasrand baumelt.',
      strInstructionsFR: null,
      strInstructionsIT: 'Mescolare lo zucchero a velo 56g e acqua gassata in un bicchiere Collins. Riempi il bicchiere di ghiaccio e aggiungi il gin. Riempi con acqua gassata e mescola. Aggiungere la scorza di limone e la spirale di arancia in modo che l\'estremità della spirale penda sul bordo del vetro.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/678xt11582481163.jpg',
      strIngredient1: 'Gin',
      strIngredient2: carbonatedWater,
      strIngredient3: powderedSugar,
      strIngredient4: 'Orange spiral',
      strIngredient5: 'Lemon peel',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: null,
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-11-10 23:21:49',
    },
    {
      idDrink: '11418',
      strDrink: 'Gin Squirt',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Stir gin, grenadine, and powdered sugar with ice and strain into a highball glass over ice cubes. Fill with carbonated water and stir. Decorate with the pineapple chunks and the strawberries and serve.',
      strInstructionsES: null,
      strInstructionsDE: null,
      strInstructionsFR: null,
      strInstructionsIT: 'Mescolare gin, granatina e zucchero a velo con ghiaccio e filtrare in un bicchiere highball su cubetti di ghiaccio. Riempi con acqua gassata e mescola. Decorare con i pezzi di ananas e le fragole e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/xrbhz61504883702.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Grenadine',
      strIngredient3: powderedSugar,
      strIngredient4: 'Pineapple',
      strIngredient5: 'Strawberries',
      strIngredient6: carbonatedWater,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '1 tsp ',
      strMeasure3: '1 tblsp ',
      strMeasure4: '3 chunks',
      strMeasure5: '2 ',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-08 16:15:02',
    },
    {
      idDrink: '17230',
      strDrink: 'Gin Rickey',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Half-fill a tall glass with ice. Mix the gin and Grenadine together and pour over the ice. Add the lime or lemon juice and top off with soda water. Decorate the glass with lime and/or lemon slices.',
      strInstructionsES: null,
      strInstructionsDE: 'Füllen Sie ein hohes Glas halb mit Eis. Gin und Grenadine vermischen und über das Eis gießen. Limetten- oder Zitronensaft hinzufügen und mit Sodawasser auffüllen. Das Glas mit Limetten- und/oder Zitronenscheiben dekorieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Riempi a metà un bicchiere alto di ghiaccio.\r\nMescolare il gin e la Grenadine e versare sul ghiaccio.\r\nAggiungere il succo di lime o limone e completare con acqua gassata.\r\nDecorare il bicchiere con lime e / o fettine di limone.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/s00d6f1504883945.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Grenadine',
      strIngredient3: 'lemon',
      strIngredient4: sodaWater,
      strIngredient5: 'Lime',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '1 tsp ',
      strMeasure3: juiceOf12,
      strMeasure4: 'Top up with',
      strMeasure5: 'Garnish',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-08 16:19:05',
    },
    {
      idDrink: '11419',
      strDrink: 'Gin Swizzle',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'In a shaker half-filled with ice cubes, combine the lime juice, sugar, gin, and bitters. Shake well. Almost fill a colling glass with ice cubes. Stir until the glass is frosted. Strain the mixture in the shaker into the glass and add the club soda.',
      strInstructionsES: null,
      strInstructionsDE: 'In einem Shaker, der halb mit Eiswürfeln gefüllt ist, Limettensaft, Zucker, Gin und Bitter vermengen. Gut schütteln. Füllen Sie ein gekühltes Glas mit Eiswürfel. Rühren Sie, bis das Glas mattiert ist. Die Mischung im Shaker in das Glas abseihen und das Club-Soda hinzufügen.',
      strInstructionsFR: null,
      strInstructionsIT: 'In uno shaker riempito a metà con cubetti di ghiaccio, unisci il succo di lime, lo zucchero, il gin e il bitter, agitare bene. Riempi quasi a l\'orlo un bicchiere Collins con dei cubetti di ghiaccio. Mescolare fino a quando il bicchiere è ghiacciato. Filtrare la miscela nello shaker e versala nel bicchiere, infine aggiungere la soda club.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/sybce31504884026.jpg',
      strIngredient1: 'Lime juice',
      strIngredient2: 'Sugar',
      strIngredient3: 'Gin',
      strIngredient4: 'Bitters',
      strIngredient5: 'Club soda',
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz ',
      strMeasure2: '1 tsp superfine ',
      strMeasure3: '2 oz ',
      strMeasure4: '1 dash ',
      strMeasure5: '3 oz ',
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-08 16:20:26',
    },
    {
      idDrink: '178342',
      strDrink: 'Gin and Soda',
      strDrinkAlternate: null,
      strTags: 'Clear,Alcoholic',
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Pour the Gin and Soda water into a highball glass almost filled with ice cubes.\r\nStir well.\r\nGarnish with the lime wedge.',
      strInstructionsES: null,
      strInstructionsDE: null,
      strInstructionsFR: null,
      strInstructionsIT: 'Versare il Gin e l\'acqua di seltz in un bicchiere highball riempito di cubetti di ghiaccio.\r\nMescolare bene.\r\nGuarnire con lo spicchio di lime.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/nzlyc81605905755.jpg',
      strIngredient1: 'Gin',
      strIngredient2: sodaWater,
      strIngredient3: 'Lime',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz',
      strMeasure2: '5 oz',
      strMeasure3: '1/4',
      strMeasure4: '',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: null,
    },
    {
      idDrink: '11403',
      strDrink: 'Gin And Tonic',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Pour the gin and the tonic water into a highball glass almost filled with ice cubes. Stir well. Garnish with the lime wedge.',
      strInstructionsES: null,
      strInstructionsDE: 'Gießen Sie den Gin und das Tonic Water in ein Highball-Glas, das fast mit Eiswürfeln gefüllt ist. Gut umrühren. Mit dem Limettenkeil garnieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Versare il gin e l\'acqua tonica in un bicchiere highball quasi riempito di cubetti di ghiaccio. Guarnire con lo spicchio di lime. Mescolare bene.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/k0508k1668422436.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Tonic water',
      strIngredient3: 'Lime',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '5 oz ',
      strMeasure3: '1 ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://pxhere.com/en/photo/1556755',
      strImageAttribution: 'pxhere.com',
      strCreativeCommonsConfirmed: 'Yes',
      dateModified: '2016-08-28 18:37:11',
    },
    {
      idDrink: '12057',
      strDrink: 'Royal Gin Fizz',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Shake all ingredients (except carbonated water) with ice and strain into a highball glass over two ice cubes. Fill with carbonated water, stir, and serve.',
      strInstructionsES: null,
      strInstructionsDE: 'Alle Zutaten (außer kohlensäurehaltigem Wasser) mit Eis schütteln und über zwei Eiswürfel in ein Highball-Glas sieben. Mit kohlensäurehaltigem Wasser auffüllen, umrühren und servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare tutti gli ingredienti (eccetto l\'acqua gassata) con ghiaccio e filtrare in un bicchiere highball su due cubetti di ghiaccio. Riempi con acqua gassata, mescola e servi',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/pe1x1c1504735672.jpg',
      strIngredient1: 'Gin',
      strIngredient2: 'Lemon',
      strIngredient3: powderedSugar,
      strIngredient4: 'Egg',
      strIngredient5: carbonatedWater,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: juiceOf12,
      strMeasure3: '1 tsp ',
      strMeasure4: '1 whole ',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-06 23:07:52',
    },
    {
      idDrink: '178367',
      strDrink: 'Ramos Gin Fizz',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Prepare all the ingredients on the counter to be able to work well and quickly, especially the cream and egg white.\r\n\r\nPour all the ingredients into a shaker.\r\n\r\nShake vigorously for 1 minute: cream and egg white must be mixed perfectly, so don\'t rush.\r\n\r\nNow open the shaker and put some ice and shake for 1-2 minutes. It depends on how long you can resist!\r\n\r\nPour into a highball glass, add a splash of soda and garnish to taste.\r\n\r\nRamos Gin Fizz was once drunk as an invigorating drink or even as a breakfast, try it as an aperitif and after dinner and you will discover a little gem now lost.',
      strInstructionsES: null,
      strInstructionsDE: 'Bereiten Sie alle Zutaten auf der Theke vor, um gut und schnell arbeiten zu können, insbesondere die Sahne und das Eiweiß.\r\nAlle Zutaten, bis auf das Soda, in einen Shaker geben.\r\n1 Minute kräftig schütteln: Sahne und Eiweiß müssen sich perfekt vermischen, also keine Eile.\r\nJetzt den Shaker öffnen und etwas Eis hinzugeben und 1-2 Minuten schütteln. Es kommt darauf an, wie lange du widerstehen kannst!\r\nIn ein Longdrinkglas gießen, einen Spritzer Soda hinzugeben und nach Belieben garnieren.\r\nRamos Gin Fizz wurde einst als belebendes Getränk oder sogar als Frühstück getrunken, probieren Sie es als Aperitif und nach dem Abendessen und Sie werden ein kleines Juwel entdecken, das jetzt verloren gegangen ist.',
      strInstructionsFR: null,
      strInstructionsIT: 'Preparate tutti gli ingredienti sul bancone per poter lavorare bene e velocemente, soprattutto la panna e l’albume d’uovo.\r\nVersate tutti gli ingredienti, a parte la soda, in uno shaker.\r\nAgitate energicamente per 1 minuto: panna ed albume si devono mescolare alla perfezione, quindi non abbiate fretta.\r\nAdesso aprite lo shaker e mettete un po’ di ghiaccio e agitate per 1-2 minuti. Dipende da quanto riuscite a resistere!\r\nVersate in un bicchiere highball, aggiungete uno schizzo di soda e guarnite a piacere.\r\nUna volta il Ramos Gin Fizz era bevuto come drink corroborante o addirittura come colazione, provatelo come aperitivo e nel dopo cena e scoprirete un piccolo gioiello ormai perduto.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/967t911643844053.jpg',
      strIngredient1: 'Gin',
      strIngredient2: lemonJuice,
      strIngredient3: 'Sugar Syrup',
      strIngredient4: 'Cream',
      strIngredient5: 'Egg White',
      strIngredient6: 'Vanilla extract',
      strIngredient7: sodaWater,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '4.5 cL',
      strMeasure2: '3 cl',
      strMeasure3: '3 cl',
      strMeasure4: '6 cl',
      strMeasure5: '1',
      strMeasure6: '2 drop',
      strMeasure7: '2 cl',
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: 'https://cdn.diffords.com/contrib/stock-images/2021/08/610d32bab0377.jpg',
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: null,
    },
    {
      idDrink: '178314',
      strDrink: 'Gin Basil Smash',
      strDrinkAlternate: null,
      strTags: 'Europe,Summer',
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Muddle Basil leaves (~ 10) with Suggar Syrup in a shaker. Add Gin an Lemon Juice.\r\nFilter and serve in a tumbler with ice',
      strInstructionsES: null,
      strInstructionsDE: null,
      strInstructionsFR: null,
      strInstructionsIT: 'Pestare le foglie di basilico (~ 10) con lo sciroppo di zucchero in uno shaker. Aggiungi gin e succo di limone. Filtrare e servire in un tumbler con ghiaccio',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/jqh2141572807327.jpg',
      strIngredient1: 'Gin',
      strIngredient2: lemonJuice,
      strIngredient3: 'Sugar Syrup',
      strIngredient4: 'Basil',
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '6 cl',
      strMeasure2: '2 cl',
      strMeasure3: '2 cl',
      strMeasure4: 'Whole',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: null,
    },
    {
      idDrink: '12224',
      strDrink: 'Sloe Gin Cocktail',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: ordinaryDrink,
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Cocktail glass',
      strInstructions: 'Stir all ingredients with ice, strain into a cocktail glass, and serve.',
      strInstructionsES: null,
      strInstructionsDE: 'Alle Zutaten mit Eis verrühren, in ein Cocktailglas abseihen und servieren.',
      strInstructionsFR: null,
      strInstructionsIT: 'Mescolare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/d7mo481504889531.jpg',
      strIngredient1: 'Sloe gin',
      strIngredient2: 'Dry Vermouth',
      strIngredient3: 'Orange bitters',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz ',
      strMeasure2: '1/4 tsp ',
      strMeasure3: '1 dash ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-09-08 17:52:12',
    },
    {
      idDrink: '12718',
      strDrink: 'Pineapple Gingerale Smoothie',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Other / Unknown',
      strIBA: null,
      strAlcoholic: 'Non alcoholic',
      strGlass: highballGlass,
      strInstructions: 'Throw everything into a blender and liquify.',
      strInstructionsES: null,
      strInstructionsDE: 'Alles in einen Mixer geben und aufschlagen.',
      strInstructionsFR: null,
      strInstructionsIT: 'Getta tutto in un frullatore e liquida.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/eg9i1d1487603469.jpg',
      strIngredient1: 'Ginger',
      strIngredient2: 'Pineapple',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1/4 inch ',
      strMeasure2: '1/2 ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-02-20 15:11:09',
    },
  ],
};

export const drinksNameAquamarine = {
  drinks: [
    {
      idDrink: '178319',
      strDrink: 'Aquamarine',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Martini Glass',
      strInstructions: 'Shake well in a shaker with ice.\r\nStrain in a martini glass.',
      strInstructionsES: 'Agite bien en una coctelera con hielo. Cuela en una copa de Martini.',
      strInstructionsDE: null,
      strInstructionsFR: null,
      strInstructionsIT: 'Shakerare bene in uno shaker con ghiaccio.\r\nFiltrare in una coppetta Martini.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/zvsre31572902738.jpg',
      strIngredient1: 'Hpnotiq',
      strIngredient2: 'Pineapple Juice',
      strIngredient3: 'Banana Liqueur',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 oz',
      strMeasure2: '1 oz',
      strMeasure3: '1 oz',
      strMeasure4: '',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: null,
    },
  ],
};
